file:
  storage:
    location: storage
server:
  port: 8082
  error:
    whitelabel:
      enabled: false




spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  datasource:
    url: jdbc:mysql://localhost:3306/green?useSSL=false
    username: root
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver